### PR TITLE
bug: typo

### PR DESCRIPTION
**Pull request by philschatz**
just a small typo

### CODE REVIEW

**Comment by c0ldcalamari** [comment]
Do we need to do anything for the ChromeDriver dependency that is failing the circle integration test?

**Comment by m1yag1** [comment]
@c0ldcalamari Did you rebase latest from master? the updates were done.

**Comment by c0ldcalamari** [comment]
@m1yag1 I did not, but I remember this dependency failure, from somewhere - this is enough information for me, thank you!

**Comment by tomjw64** [comment]
@philschatz This will probably pass the tests after a rebase

**Pull request merged**
