### PR TITLE
adding verification for second error message in colid field - incorrect colid

### PR DESCRIPTION
**Pull request by omehes**
verification for incorrect colid error message

### CODE REVIEW

**Comment by omehes** [comment]
Note, that I had to add sleep time to ```def click_create_button(self):``` because the test was failing and passing due to being to fast.

**Comment by therealmarv** [comment]
It seems `ci/circleci: integration-test` is still failing (click on Details).

**Comment by omehes** [comment]
that is weird. that file (test_incorrect_col_id_error) does not exist anymore. I deleted it before commiting and pushing the branch. the file where the new test is, is "test_modal_field_errors.py" and that passed.

**Comment by omehes** [comment]
@therealmarv I did some little changes and had to force push the changes but now it looks good. Integration tests passed...

**Pull request merged**
